#Load EMLo (No need to run)

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
b1 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch1.npy", allow_pickle=True)
b2 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch2.npy", allow_pickle=True)
b3 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch3.npy", allow_pickle=True)
b4 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch4.npy", allow_pickle=True)
b5 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch5.npy", allow_pickle=True)
b6 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch6.npy", allow_pickle=True)
b7 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch7.npy", allow_pickle=True)
b8 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch8.npy", allow_pickle=True)
b9 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch9.npy", allow_pickle=True)
b10 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch10.npy", allow_pickle=True)
b11 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch11.npy", allow_pickle=True)
b12 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch12.npy", allow_pickle=True)
b13 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch13.npy", allow_pickle=True)

In [0]:
batches = np.concatenate((b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12))

In [0]:
print(len(b13), len(batches), type(b13), type(batches))
print(len(b13[0]), len(batches[0]), type(b13[0]),type(batches[0]))
print(len(b13[0][0]), len(batches[0][0]), type(b13[0][0]),type(batches[0][0]))
print(type(b13[0][0][0]), type(batches[0][0][0]))

In [0]:
print(b10.shape, b1.shape)
new_b13 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch13.npy", allow_pickle=True)

In [0]:
b13 = np.load("/content/drive/My Drive/Colab Notebooks/ELMoData/elmo_titles_batch13.npy", allow_pickle=True)
print( len( b13 ))
updated_b13 = list()
for elem in b13 : 
  if elem.shape == (100,1024):
    updated_b13.append( elem )
print(len(updated_b13))
b13 = np.stack( updated_b13, axis=0 )

37
36


In [0]:
batches = np.concatenate((batches, b13))
batches.shape

(886, 100, 1024)

In [0]:
batches = batches.reshape(88600, 1024)
batches.shape

(88600, 1024)

In [0]:
np.save('/content/drive/My Drive/Colab Notebooks/ELMoData/all_batches.npy', batches, allow_pickle=True)

#Initial Downloads and imports

In [0]:
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

from datetime import datetime
from dateutil.parser import parse

from sklearn import svm
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle, resample

import gensim
import warnings
warnings.filterwarnings(action='ignore', category=UserWarning, module='gensim')
warnings.simplefilter(action='ignore', category=FutureWarning)
from gensim.models.keyedvectors import KeyedVectors
from gensim.models import Word2Vec
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from gensim.models.phrases import Phrases, Phraser

import matplotlib.pyplot as plt

import nltk
nltk.download('punkt')
from nltk import word_tokenize

import sys
import csv
csv.field_size_limit(sys.maxsize)

from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Model
from keras.layers import Dense, Dropout, Activation, Lambda, Input, concatenate
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM, SimpleRNN, GRU
from keras.preprocessing.text import Tokenizer
from collections import defaultdict
from keras.layers.convolutional import Convolution1D

1.14.0
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Using TensorFlow backend.


In [0]:
# Mount drive to import necessary files:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
def prepare_data(titles):
  """ Method to load in data and prepare final pandas.DataFrame for inputting
      machine learning algorithms

  Parameters
  ----------
  titles : str
      File name of numpy array of title document embedding vectors
  content : str
      File name of numpy array of content document embedding vectors
  """
  # file path for main csv file of all text data
  path = '/content/drive/My Drive/Colab Notebooks/MSc Project 2019 Aaron Dougherty csvData/title_contentSTOP.csv'
  # read in main csv file into pandas.DataFrame
  df = pd.read_csv(path, encoding='ISO-8859-1', engine='python', error_bad_lines=False)
  # file path for sentiment and finance data
  path2 = '/content/drive/My Drive/Colab Notebooks/MSc Project 2019 Aaron Dougherty csvData/sent_fin.csv'
  # read in csv fiel into pandas.DataFrame
  sent_fin = pd.read_csv(path2, encoding='ISO-8859-1', engine='python', error_bad_lines=False)
  # remove useless columns
  sent_fin.drop('Unnamed: 0', axis=1, inplace=True)
  df.drop('Unnamed: 0', axis=1, inplace=True)
  df.drop('content', axis=1, inplace=True)
  print('initial dataframes loaded')
  # load in document vectors
  titleVecs = np.load("/content/drive/My Drive/Colab Notebooks/MSc Project 2019 Aaron Dougherty ELMoData/" + titles,
                      allow_pickle=True)
  print('word embeddings loaded')
  # load document vectors into data frame
  df['title_vectors'] = pd.Series(titleVecs.tolist())
  print('word embeddings added to dataframe')
  
  for index, row in df.iterrows(): # convert vectors to numpy arrays
    row['title_vectors'] = np.array(row['title_vectors'])
  print('text converted to numpy arrays')
  # find mean document vector per date
  result_df = df.groupby('date')['title_vectors'].apply(np.mean).to_frame('Title')
  print('mean of document vectors for each date found')
  # recombine data frames created above
  result_df = result_df.reset_index().rename(columns={"date" : "Date"})
  # merge text data with finance and sentiment data
  result_df = result_df.merge(sent_fin, how='inner', on='Date')
  return result_df

def explode_df(df):
  """ Method to explode document vectors into on column per value for feeding
      into machine learning algorithms

  Parameters
  ----------
  df : pandas.DataFrame
      data frame to expand
  """
  df1 = df.iloc[:, 0:2]
  df2 = df.iloc[:, 2:]
  df2['Date'] = df1['Date']
  splitTitle = pd.DataFrame(df1['Title'].tolist())
  splitTitle['Date'] = pd.Series(df1['Date'])
  final = splitTitle.merge(df2, how='inner', on='Date')
  return final

import math

def removeNANs(df):
  """ Method to remove rows with no text

  Parameters
  ----------
  df : pandas.DataFrame
      Data frame to remove rows from
  """
  
  for index, row in df.iterrows():
    # check is row/column contains NAN type
    if math.isnan(row['Title'][0]):
      print(index)
      df.drop([index], inplace=True)
    # check is row/column contains NAN type
    # if type(row['Content']) is not type(string):
    #   df.drop([index], inplace=True)
  return df

In [0]:
# prepare final data frame
df = prepare_data('all_batches.npy')

initial dataframes loaded
word embeddings loaded
word embeddings added to dataframe
text converted to numpy arrays
mean of document vectors for each date found


In [0]:
df = removeNANs(df)

375


In [0]:
df.shape

(375, 17)

In [0]:
df = explode_df(df)

#Training/Development/Testing Split

In [0]:
def shuffle_df(df):
  """ Method to shuffle rows of a data frame

  Parameters
  ----------
  df : pandas.DataFrame
      Data frame to shuffle
  """
  index = df.index # record data frame indexes
  df = shuffle(df) # ScikitLearn's shuffle method
  df.index = index # reset indexes
  return df

In [0]:
# shuffle data frame
df = shuffle_df(df)
df.head()

In [0]:
# split into X and y
X = df.iloc[:, 0:-1] # set to -8 to remove financial data and -1 to include; -15 removes sentiment
X.drop('Date', axis=1, inplace=True)
y = df[['Date', 'Direction']]
# split into training, development and testing sets
X_train, X_other, y_train, y_other = train_test_split(X, y, test_size=0.2, shuffle=False)
X_dev, X_test, y_dev, y_test = train_test_split(X_other, y_other, test_size=0.5, shuffle=False)
# remove useless columns
y_dev.drop('Date', axis=1, inplace=True)
y_test.drop('Date', axis=1, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


##Dealing with class imbalance:

In [0]:
def recombine(X, y):
  """ Method to recombine the X and y

  Parameters
  ----------
  X : pandas.DataFrame
      Data frame containing X variables
  y : pandas.DataFrame
      Data frame containing y variables
  """
  train = X_train
  train['Direction'] = y_train['Direction'] # combine X and y
  return train

def address_class_imbalance(df, minority_classification, majority_classification,
                            minority_target_samples, majority_target_samples):
  """ Method to remove class imbalance within a data set for binary classification

  Parameters
  ----------
  df : pandas.DataFrame
      Data frame to check for and remove class imbalances from
  minority_classification : int
      the minority class
  majority_classification : int
      the majority class
  minority_target_samples: int
      number of samples to upsample to
  majority_target_samples: int
      number of samples to downsample to
  """
  # Split data frame in 2, 1 for each class
  minority_class = df[df.Direction == minority_classification]
  majority_class = df[df.Direction == majority_classification]
 
  # down sample majority and up sample minority the desired amount using helper
  # methods
  downsampled_majority = downsample_majority(majority_class, majority_target_samples)
  upsampled_minority = upsample_minority(minority_class, minority_target_samples)
  
  # combine newly sampled data frames
  new_df = upsampled_minority
  new_df = new_df.append(downsampled_majority, ignore_index=True)

  return new_df

# Upsample helper method
def upsample_minority(minority_class, target_samples):
  """ Method to up sample the minority class

  Parameters
  ----------
  minority_class : int
      the minority class
  target_samples: int
      number of samples to upsample to
  """
  return resample(minority_class, replace = True, n_samples = target_samples)

# Downsample helper method
def downsample_majority(majority_class, target_samples):
  """ Method to down sample the majority class

  Parameters
  ----------
  majority_class : int
      the majority class
  majority_target_samples: int
      number of samples to downsample to
  """
  return resample(majority_class, replace = False, n_samples = target_samples)

def find_y_mid_point(df):
  """ Method to find the mid-point between to class counts

  Parameters
  ----------
  df : pandas.DataFrame
      dataframe to find midpoint in between 2 unbalanced classes
  """
  # count number of rows belonging to each binary class
  count_class_0, count_class_1 = df.Direction.value_counts()
  # calculate mid-point
  mid_point = int(count_class_1 + ((count_class_0 - count_class_1)/2))
  return mid_point

In [0]:
# rebalance classes using mis point (up and down sample classes equally)
train = recombine(X_train, y_train) # recombine training sets
target_sample = find_y_mid_point(train) # determine target sample value
# up and down sample the classes to remove imbalance
train = address_class_imbalance(train, 1, 0, target_sample, target_sample)
train = shuffle_df(train) # shuffle the new training set
# Split training set back into X and y
X_train = train.iloc[:, 0:-1]
y_train = train[['Direction']]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':


In [0]:
y_train

In [0]:
minority_class = train[train.Direction == 1]
majority_class = train[train.Direction == 0]
print(len(minority_class), len(majority_class))

150 150


In [0]:
X_train

#SVM

without sentiment or finance

In [0]:
# ELMo
# SVM_classifier = svm.SVC(kernel='sigmoid')
SVM_classifier = svm.LinearSVC()

#Train the model using the training sets
SVM_classifier.fit(X_train, y_train)

#Predict the response for test dataset
y_predSVM = SVM_classifier.predict(X_dev)

print(classification_report(y_dev, y_predSVM))
print(confusion_matrix(y_dev, y_predSVM))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.58      0.74      0.65        19
           1       0.62      0.44      0.52        18

    accuracy                           0.59        37
   macro avg       0.60      0.59      0.58        37
weighted avg       0.60      0.59      0.59        37

[[14  5]
 [10  8]]


without finance data but with sentiment

In [0]:
# ELMo
# SVM_classifier = svm.SVC(kernel='sigmoid')
SVM_classifier = svm.LinearSVC()

#Train the model using the training sets
SVM_classifier.fit(X_train, y_train)

#Predict the response for test dataset
y_predSVM = SVM_classifier.predict(X_dev)

print(classification_report(y_dev, y_predSVM))
print(confusion_matrix(y_dev, y_predSVM))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.65      0.68      0.67        19
           1       0.65      0.61      0.63        18

    accuracy                           0.65        37
   macro avg       0.65      0.65      0.65        37
weighted avg       0.65      0.65      0.65        37

[[13  6]
 [ 7 11]]


with finance data and sentiment

In [0]:
# ELMo

# SVM_classifier = svm.SVC(kernel='sigmoid')
SVM_classifier = svm.LinearSVC()

#Train the model using the training sets
SVM_classifier.fit(X_train, y_train)

#Predict the response for test dataset
y_predSVM = SVM_classifier.predict(X_dev)

print(classification_report(y_dev, y_predSVM))
print(confusion_matrix(y_dev, y_predSVM))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.57      0.63      0.60        19
           1       0.56      0.50      0.53        18

    accuracy                           0.57        37
   macro avg       0.57      0.57      0.56        37
weighted avg       0.57      0.57      0.57        37

[[12  7]
 [ 9  9]]


#RF

without finance or sentiment

In [0]:
# ELMo
rndm_fc = RandomForestClassifier()
rndm_fc = rndm_fc.fit(X_train, y_train)
y_predRF = rndm_fc.predict(X_dev)

print(classification_report(y_dev, y_predRF))
print(confusion_matrix(y_dev, y_predRF))

              precision    recall  f1-score   support

           0       0.58      0.79      0.67        19
           1       0.64      0.39      0.48        18

    accuracy                           0.59        37
   macro avg       0.61      0.59      0.57        37
weighted avg       0.61      0.59      0.58        37

[[15  4]
 [11  7]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


without finance but with sentiment

In [0]:
# ELMo
rndm_fc = RandomForestClassifier()
rndm_fc = rndm_fc.fit(X_train, y_train)
y_predRF = rndm_fc.predict(X_dev)

print(classification_report(y_dev, y_predRF))
print(confusion_matrix(y_dev, y_predRF))

              precision    recall  f1-score   support

           0       0.58      0.79      0.67        19
           1       0.64      0.39      0.48        18

    accuracy                           0.59        37
   macro avg       0.61      0.59      0.57        37
weighted avg       0.61      0.59      0.58        37

[[15  4]
 [11  7]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


with finance data and sentiment

In [0]:
# ELMo
rndm_fc = RandomForestClassifier()
rndm_fc = rndm_fc.fit(X_train, y_train)
y_predRF = rndm_fc.predict(X_dev)

print(classification_report(y_dev, y_predRF))
print(confusion_matrix(y_dev, y_predRF))

              precision    recall  f1-score   support

           0       0.55      0.84      0.67        19
           1       0.62      0.28      0.38        18

    accuracy                           0.57        37
   macro avg       0.59      0.56      0.53        37
weighted avg       0.59      0.57      0.53        37

[[16  3]
 [13  5]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


#GBM

without finance or sentiment

In [0]:
# ELMo
GBM = GradientBoostingClassifier()
GBM = GBM.fit(X_train, y_train)
y_predGBM = GBM.predict(X_dev)

print(classification_report(y_dev, y_predGBM))
print(confusion_matrix(y_dev, y_predGBM))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.63      0.89      0.74        19
           1       0.80      0.44      0.57        18

    accuracy                           0.68        37
   macro avg       0.71      0.67      0.66        37
weighted avg       0.71      0.68      0.66        37

[[17  2]
 [10  8]]


without finance but with sentiment

In [0]:
# ELMo
GBM = GradientBoostingClassifier()
GBM = GBM.fit(X_train, y_train)
y_predGBM = GBM.predict(X_dev)

print(classification_report(y_dev, y_predGBM))
print(confusion_matrix(y_dev, y_predGBM))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.60      0.79      0.68        19
           1       0.67      0.44      0.53        18

    accuracy                           0.62        37
   macro avg       0.63      0.62      0.61        37
weighted avg       0.63      0.62      0.61        37

[[15  4]
 [10  8]]


with finance and sentiment

In [0]:
# ELMo
GBM = GradientBoostingClassifier()
GBM = GBM.fit(X_train, y_train)
y_predGBM = GBM.predict(X_dev)

print(classification_report(y_dev, y_predGBM))
print(confusion_matrix(y_dev, y_predGBM))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.64      0.84      0.73        19
           1       0.75      0.50      0.60        18

    accuracy                           0.68        37
   macro avg       0.70      0.67      0.66        37
weighted avg       0.69      0.68      0.67        37

[[16  3]
 [ 9  9]]
